### ISSUE TITLE
Old java?

### ISSUE THREAD

**Issue by jenbru86** [zocker-160/sheepit-docker-nvidia#2]
Hello, I'm new to the whole github stuff, so forgive me if I could have fixed it somehow my self..

I try to run this, but I get an error:
_"Exception in thread "main" java.lang.UnsupportedClassVersionError: com/sheepit/client/standalone/Worker has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0"_

According to this site: https://www.baeldung.com/java-lang-unsupportedclassversion 
52 = Java 8
53 = Java 9
54 = Java 10
55 = Java 11
56 = Java 12
57 = Java 13

In the docker file you specify "openjdk-8-jre".

**Comment by zocker-160** [comment]
thank you for reporting and reminding me.

The latest client moved the minimum required version from 8 to 11, which is why you got this error.
