### ISSUE TITLE
Blender failed to detect the render device

### ISSUE THREAD

**Issue by mhentschke** [zocker-160/sheepit-docker-nvidia#3]
While trying to set this up, I got the following log:

`
Feb 22 20:17:55 Preparing project   0% [>                    ]              Feb 22 20:17:57 Rendering 

Feb 22 20:17:57 Compute method: 

ERROR: Feb 22 20:17:57 Blender failed to detect the render device. Please check if you have all the necessary libraries installed and if your drivers are up to date.

Feb 22 20:17:58 Session downloads: 339.73MB @ 14.48MB/s / Uploads: 0.00MB @ 0.01MB/s

I have two GPUs, a 1050ti and a 1060 6GB, both of them work with passthrough on other containers (Tdarr Node for example) but couldn't get this one to use the GPUs. `

OS is Fedora 37

**Comment by zocker-160** [comment]
Thank you for reporting this, I can reproduce the problem, looking into it.

**Comment by zocker-160** [comment]
Fixed image should be available on docker hub in a few minutes.
